### PR TITLE
Version lock phpcs and synapse-base in composer.json

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. PHP Codesniffer and Synapse-base are locked to their current versions, rather than `dev-master`
1. Lock file is updated as well.

### Tasks
Update composer.json and lock file

### CODE REVIEW

**Comment by paulstatezny** [comment]
:pray:

**Comment by agerbens** [comment]
Should update the lock file as well :interrobang:

**Comment by agerbens** [comment]
:star:

**Comment by agerbens** [comment]
:o: Build failed

**Comment by agerbens** [comment]
:star:

**Comment by paulstatezny** [comment]
:pray:

**Comment by nearengine** [comment]
:+1:

**Pull request merged**
