### PR TITLE
Fix phpunit config (remove strict)

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. `strict` line removed from `phpunit.xml` and `phpunit.shippable.xml`
1. add following options:
```
         reportUselessTests="true"
         strictCoverage="true"
         disallowTestOutput="true"
```

### Tasks
- {{list developer tasks here}}

### Additional Notes
- https://github.com/sebastianbergmann/phpunit-documentation/issues/282

### CODE REVIEW

**Comment by bobeagan** [comment]
:+1:

**Comment by agerbens** [comment]
:o: We can't let the robots win!

**Comment by baohx2000** [comment]
:star:

**Comment by agerbens** [comment]
:+1:

**Pull request merged**
