### PR TITLE
Set APP_ENV in environment variables so they can be referenced in console commands

### PR DESCRIPTION
**Pull request by paulstatezny**
### Acceptance Criteria
1. Vagrantfile passes environment ~~and APP_NAME~~ into `syn-vagrant-project.sh`
1. `syn-vagrant-project.sh` sets it as an environment variable

### Tasks
- Modify those files

### Additional Notes
- None

### CODE REVIEW

**Comment by paulstatezny** [comment]
:star:

**Comment by paulstatezny** [comment]
(This was successful on the project repo. See hidden link above my commit.)

**Comment by agerbens** [comment]
:hand:

**Comment by agerbens** [comment]
:-1: Error on vagrant up
`Vagrantfile:15:in `block in <top (required)>': undefined local variable or method `app_name' for main:Object (NameError)`

**Comment by paulstatezny** [comment]
:star:

**Comment by nearengine** [comment]
:+1:

**Pull request merged**
