### PR TITLE
syn-vagrant file in repo that overrides the global one

### PR DESCRIPTION
**Pull request by synbot**
syn-vagrant file in repo that overrides the global one

### CODE REVIEW

**Comment by bobeagan** [comment]
Let's fix file naming to be more clear

**Comment by zpchavez** [comment]
Any suggestions?

**Comment by zpchavez** [comment]
Like that? :star:

**Comment by bobeagan** [comment]
Should the global one still be -nginx though?

**Comment by baohx2000** [comment]
we should have a general one (the -nginx.sh) then the project-specific Vagrantfile can also check for a project-specific file after that

**Comment by baohx2000** [comment]
:+1:

**Pull request merged**
