### PR TITLE
Change methods to endpoints in lively config files

### PR DESCRIPTION
**Pull request by synbot**
## Change methods to endpoints in lively config files
https://github.com/synapsestudios/lively/pull/107 renamed `methods` to `endpoints` in the lively config files. `methods` will be deprecated at some point, so this change is to update them in the template.

### Acceptance Criteria
1. Lively works as expected.

### CODE REVIEW

**Comment by bobeagan** [comment]
:pray:

**Comment by paulstatezny** [comment]
Blocked by that Lively issue.

**Comment by pcavagna** [comment]
:hand:

**Comment by paulstatezny** [comment]
:+1:

**Pull request merged**
